quarkus.mongodb.database=products_db
quarkus.mongodb.connection-string=${MONGODB_URI:mongodb://localhost:27017/?replicaSet=rs0}

kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.create.topic=invoices