# Base Local Defaults
quarkus.http.port=8081
mp.messaging.incoming.create.topic=invoices
bucket.name=invoice-bucket

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/invoice-db
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.flyway.enabled=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.migrate-at-start=true

# S3 Configuration
quarkus.s3.endpoint-override=http://localhost:4566
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=test
quarkus.s3.aws.credentials.static-provider.secret-access-key=test

# --- Kubernetes Profile Overrides ---
%k8s.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/invoice-db
%k8s.quarkus.s3.endpoint-override=http://floci-s3:4566
%k8s.kafka.bootstrap.servers=kafka:9092
%k8s.mp.messaging.incoming.create.auto.offset.reset=earliest